### ISSUE TITLE
Rails 4.2.7 - NoMethodError: undefined method `tv_nsec' when serializing DateTime AR object

### ISSUE THREAD

**Issue by alotofnoodles** [ohler55/oj#476]
I am working on Rails `4.2.7.1` &7 Ruby `2.3.0` app that is not due for upgrade and would like to use `oj` to boost the JSON serialization and deserialization time.

Running `to_json` on AR object with datetime attribute throws error `NoMethodError: undefined method tv_nsec' for Sun, 20 May 2018 10:40:18 UTC +00:00:DateTime` (Link to the sample app and steps to reproduce the issue https://github.com/alotofnoodles/oj-debug). 

I can't reproduce this on Rails 5.x, so I assume that oj only works with Active Support 5 as per documentation? Is it possible to get oj working on Rails 4.x ?

**Comment by ohler55** [comment]
I will take a look. It is odd that a DateTime is being dumped as a Time or at least thats what it looks like. Thanks for the super way to reproduce.

By the way, Rails 4.x should be mostly okay other than some minor changes in how things are encoded although maybe you have found one problem I didn't expect.

**Comment by alotofnoodles** [comment]
Hey @ohler55, any luck?

**Comment by ohler55** [comment]
Haven’t been able to get to it yet. It will require tracing rails

**Comment by alotofnoodles** [comment]
Thanks for sparing your time for this. I'll investigate this weekend and will keep you updated.

**Comment by ohler55** [comment]
I tried to run the test. Got this.
```
> rake db:migrate
/home/ohler/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/home/ohler/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
rake aborted!
SystemStackError: stack level too deep
/home/ohler/git/oj-debug/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```
Is that normal?

**Comment by alotofnoodles** [comment]
I can reproduce the error above with ruby `2.5.0`. Could you switch to `2.3.0` instead? I guess the older version of rails does not suppoer `2.5.0`

**Comment by ohler55** [comment]
Just pushed an update to the regex branch that I think will work for you.

**Comment by alotofnoodles** [comment]
I can confirm that your changes on `regex` branch fix the DateTime problem in Rails 4.2.7.1.
👍

**Comment by ohler55** [comment]
Excellent, thanks. I'll get a release out soon.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by alotofnoodles** [comment]
Yup Thanks for your help
