### ISSUE TITLE
Gem failing to install due to "error: #include nested too deeply"

### ISSUE THREAD

**Issue by kwestein** [ohler55/oj#474]
Hi @ohler55,

I have just gotten a new machine (Mac OSX) and have been unable to install the OJ gem on my project. I keep getting repeated `error: #include nested too deeply` errors.

Here is the stacktrace:
````
Installing oj 3.6.0 with native extensions
┃┃ Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
┃┃     current directory: /Users/kirstenwesteinde/.gem/ruby/2.5.1/gems/oj-3.6.0/ext/oj
┃┃ /opt/rubies/2.5.1/bin/ruby -r ./siteconf20180514-25520-917jpu.rb extconf.rb
┃┃ >>>>> Creating Makefile for ruby version 2.5.1 on x86_64-darwin17 <<<<<
┃┃ creating Makefile
┃┃ current directory: /Users/kirstenwesteinde/.gem/ruby/2.5.1/gems/oj-3.6.0/ext/oj
┃┃ make "DESTDIR=" clean
┃┃ current directory: /Users/kirstenwesteinde/.gem/ruby/2.5.1/gems/oj-3.6.0/ext/oj
┃┃ make "DESTDIR="
┃┃ compiling cache8.c
┃┃ In file included from cache8.c:2:
┃┃ In file included from /usr/include/stdlib.h:65:
┃┃ In file included from /usr/include/sys/wait.h:110:
┃┃ In file included from /usr/include/sys/resource.h:72:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /u
┃┃ sr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included
┃┃  from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ In file included from /usr/local/include/stdint.h:59:
┃┃ /usr/local/include/stdint.h:2:10: error: #include nested too deeply
┃┃ #include <stddef.h>
┃┃          ^
┃┃ /usr/local/include/stdint.h:59:11: error: #include nested too deeply
┃┃ # include <stdint.h>
┃┃           ^
┃┃ /usr/local/include/stdint.h:72:11: error: #include nested too deeply
┃┃ # include <sys/types.h>
┃┃           ^
┃┃ /usr/local/include/stdint.h:76:10: error: #include nested too deeply
┃┃ #include <limits.h>
┃┃          ^
┃┃ /usr/local/include/stdint.h:82:11: error: #include nested too deeply
┃┃ # include <inttypes.h>
┃┃           ^
┃┃ In file included from cache8.c:2:
┃┃ In file included from /usr/include/stdlib.h:65:
┃┃ In file included from /usr/include/sys/wait.h:110:
┃┃ /usr/include/sys/resource.h:197:2: error: unknown type name 'uint64_t'
┃┃         uint64_t ri_user_time;
┃┃         ^
┃┃ /usr/include/sys/resource.h:198:2: error: unknown type name 'uint64_t'
┃┃         uint64_t ri_system_time;
┃┃         ^
┃┃ /usr/include/sys/resource.h:199:2: error: unknown type name 'uint64_t'
┃┃         uint64_t ri_pkg_idle_wkups;
┃┃         ^
┃┃ /usr/include/sys/resource.h:200:2: error: unknow
┃┃ n type name 'uint64_t'
┃┃         uint64_t ri_interrupt_wkups;
┃┃         ^
┃┃ /usr/include/sys/resource.h:201:2: error: unknown type name 'uint64_t'
┃┃         uint64_t ri_pageins;
┃┃         ^
┃┃ /usr/include/sys/resource.h:202:2: error: unknown type name 'uint64_t'
┃┃         uint64_t ri_wired_size;
┃┃         ^
┃┃ /usr/include/sys/resource.h:203:2: error: unknown type name 'uint64_t'
┃┃         uint64_t ri_resident_size;
┃┃         ^
┃┃ /usr/include/sys/resource.h:204:2: error: unknown type name 'uint64_t'
┃┃         uint64_t ri_phys_footprint;
┃┃         ^
┃┃ /usr/include/sys/resource.h:205:2: error: unknown type name 'uint64_t'
┃┃         uint64_t ri_proc_start_abstime;
┃┃         ^
┃┃ /usr/include/sys/resource.h:206:2: error: unknown type name 'uint64_t'
┃┃         uint64_t ri_proc_exit_abstime;
┃┃         ^
┃┃ /usr/include/sys/resource.h:211:2: error: unknown type name 'uint64_t'
┃┃         uint64_t ri_user_time;
┃┃         ^
┃┃ /usr/include/sys/resource.h:212:2: error: unknown type name 'uint64_t'
┃┃         uint64_t ri_system_time;
┃┃         ^
┃┃ /usr/include/sys/resource.h:213:2: error: unknown type name 'uint64_t'
┃┃         uint64_t ri_pkg_idle_wkups;
┃┃         ^
┃┃ /usr/include/sys/resource.h:214:2: error: unknown type name 'uint64_t'
┃┃         uint64_t ri_interrupt_wkups;
┃┃         ^
┃┃ fatal error: too many errors emitted, stopping now [-ferror-limit=]
┃┃ 20 errors generated.
┃┃ make: *** [cache8.o] Error 1
┃┃ make failed, exit code 2
┃┃ Gem files will remain installed in /Users/kirstenwesteinde/.gem/ruby/2.5.1/gems/oj-3.6.0 for inspection.
┃┃ Results logged to
┃┃ /Users/kirstenwesteinde/.gem/ruby/2.5.1/extensions/x86_64-darwin-17/2.5.0-static/oj-3.6.0/gem_make.out
┃┃ An error occurred while installing oj (3.6.0), and Bundler cannot continue.
┃┃ Make sure that `gem install oj -v '3.6.0'` succeeds before bundling.
````

I cannot find reports of this anywhere. The errors are coming from the files in the ext folder, I think it is related to: https://stackoverflow.com/questions/6021720/c-nested-include-avoiding-include-nested-too-deeply-error?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa, but if so it should be affecting more than just me?

Any ideas?

**Comment by ohler55** [comment]
From the message it seem to imply that you should go to the App Store and check updates. Maybe check the version of Xcode. I am on macOS 10.12.6 and clang version 9.0.0. I'll update tonight and see if I have any issues.

**Comment by ohler55** [comment]
Works with 10.13.4 and clang 9.1.0. What macOS version and clang version are you using?

**Comment by kwestein** [comment]
Thanks for the quick response and for your help 🙏 

I have triple checked that I am up to date on all my software. I have no updates pending in the app store.

My machine is running 10.13.4 as well, with XCode 9.3 which I believe means clang 9.1.0. Not sure what else could be contributing to this error 🙈

**Comment by ohler55** [comment]
An you try a different gem? One that needs a compile.

**Comment by kwestein** [comment]
Good call. I just tried installing the jekyll gem and it failed with the same error. It must be something wrong with my system setup.

Thank you for you help

**Comment by ohler55** [comment]
Sorry we couldn't get it solved. It has to be frustrating.
