### ISSUE TITLE
version 2.1.6 can not compile in mingw32 ruby 2.1.6

### ISSUE THREAD

**Issue by Eric-Guo** [ohler55/oj#234]
C:/Ruby21/lib/ruby/gems/2.1.0/extensions/x86-mingw32/2.1.0/oj-2.12.6/gem_make.out
```
C:/Ruby21/bin/ruby.exe -r ./siteconf20150506-2248-1oh1bxi.rb extconf.rb
>>>>> Creating Makefile for ruby version 2.1.6 on i386-mingw32 <<<<<
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating oj-i386-mingw32.def
compiling cache8.c
compiling circarray.c
compiling compat.c
compiling dump.c
dump.c: In function 'dump_time':
dump.c:1034:72: error: expected ')' before ';' token
dump.c:1109:1: error: expected ',' or ';' before '}' token
dump.c:1112:1: error: invalid storage class for function 'dump_ruby_time'
dump.c:1119:1: error: invalid storage class for function 'dump_xml_time'
dump.c:1219:1: error: invalid storage class for function 'dump_data_strict'
dump.c:1232:1: error: invalid storage class for function 'dump_data_null'
dump.c:1245:1: error: invalid storage class for function 'dump_data_comp'
dump.c:1308:1: error: invalid storage class for function 'dump_data_obj'
dump.c:1352:1: error: invalid storage class for function 'dump_obj_comp'
dump.c:1413:1: error: invalid storage class for function 'dump_obj_obj'
dump.c:1489:1: error: invalid storage class for function 'dump_obj_attrs'
dump.c:1682:1: error: invalid storage class for function 'dump_struct_comp'
dump.c:1721:1: error: invalid storage class for function 'dump_struct_obj'
dump.c:1808:1: error: invalid storage class for function 'dump_odd'
dump.c:1891:1: error: invalid storage class for function 'raise_strict'
dump.c:1896:1: error: invalid storage class for function 'dump_val'
dump.c:2111:1: error: invalid storage class for function 'dump_chars'
dump.c:2121:1: error: invalid storage class for function 'dump_leaf_str'
dump.c:2137:1: error: invalid storage class for function 'dump_leaf_fixnum'
dump.c:2157:1: error: invalid storage class for function 'dump_leaf_float'
dump.c:2173:1: error: invalid storage class for function 'dump_leaf_array'
dump.c:2211:1: error: invalid storage class for function 'dump_leaf_hash'
dump.c:2251:1: error: invalid storage class for function 'dump_leaf'
dump.c:2327:1: error: invalid storage class for function 'key_check'
dump.c:2336:1: error: invalid storage class for function 'push_type'
dump.c:2348:1: error: invalid storage class for function 'maybe_comma'
dump.c:2530:1: error: expected declaration or statement at end of input
dump.c:1034:16: warning: unused variable 'nsec' [-Wunused-variable]
dump.c:1032:13: warning: unused variable 'sec' [-Wunused-variable]
dump.c:1026:11: warning: unused variable 'one' [-Wunused-variable]
dump.c:1025:11: warning: unused variable 'neg' [-Wunused-variable]
dump.c:1024:12: warning: unused variable 'dot' [-Wunused-variable]
dump.c:1023:11: warning: unused variable 'size' [-Wunused-variable]
dump.c:1022:12: warning: unused variable 'b' [-Wunused-variable]
dump.c: At top level:
dump.c:61:13: warning: 'raise_strict' used but never defined [enabled by default]
dump.c:62:13: warning: 'dump_val' used but never defined [enabled by default]
dump.c:97:13: warning: 'dump_obj_attrs' used but never defined [enabled by default]
dump.c:105:13: warning: 'dump_leaf' used but never defined [enabled by default]
dump.c:84:13: warning: 'dump_ruby_time' declared 'static' but never defined [-Wunused-function]
dump.c:85:13: warning: 'dump_xml_time' declared 'static' but never defined [-Wunused-function]
dump.c:86:13: warning: 'dump_data_strict' declared 'static' but never defined [-Wunused-function]
dump.c:87:13: warning: 'dump_data_null' declared 'static' but never defined [-Wunused-function]
dump.c:88:13: warning: 'dump_data_comp' declared 'static' but never defined [-Wunused-function]
dump.c:89:13: warning: 'dump_data_obj' declared 'static' but never defined [-Wunused-function]
dump.c:90:13: warning: 'dump_obj_comp' declared 'static' but never defined [-Wunused-function]
dump.c:91:13: warning: 'dump_obj_obj' declared 'static' but never defined [-Wunused-function]
dump.c:92:13: warning: 'dump_struct_comp' declared 'static' but never defined [-Wunused-function]
dump.c:93:13: warning: 'dump_struct_obj' declared 'static' but never defined [-Wunused-function]
dump.c:98:13: warning: 'dump_odd' declared 'static' but never defined [-Wunused-function]
dump.c:106:13: warning: 'dump_leaf_str' declared 'static' but never defined [-Wunused-function]
dump.c:107:13: warning: 'dump_leaf_fixnum' declared 'static' but never defined [-Wunused-function]
dump.c:108:13: warning: 'dump_leaf_float' declared 'static' but never defined [-Wunused-function]
dump.c:109:13: warning: 'dump_leaf_array' declared 'static' but never defined [-Wunused-function]
dump.c:110:13: warning: 'dump_leaf_hash' declared 'static' but never defined [-Wunused-function]
make: *** [dump.o] Error 1

make failed, exit code 2
```
