### ISSUE TITLE
Oj.load in object mode is broken in 2.1.2

### ISSUE THREAD

**Issue by take-five** [ohler55/oj#97]
Hi Peter!

It seems that something is broken since 2.1.x release. I've found a bug when this code failed:

``` ruby
require 'oj'

class TestException < StandardError
  attr_reader :original_error

  def initialize(original_error)
    super(original_error.message)

    set_backtrace(original_error.backtrace)
  end
end

e = TestException.new(RuntimeError.new)

p Oj.load(Oj.dump(e, :mode => :object), :mode => :object)
```

it produces error:

```
oj_test.rb:7:in `initialize': undefined method `message' for "RuntimeError":String (NoMethodError)
    from oj_test.rb:15:in `load'
    from oj_test.rb:15:in `<main>'
```

Though works perfectly on 2.0.14
