### ISSUE TITLE
undefined method new

### ISSUE THREAD

**Issue by micke** [ohler55/oj#151]
We started getting this exception after upgrading to v2.9.2:

```
undefined method `new' for #<TypeError: no implicit conversion of nil into String>
```

Stack trace

```
multi_json (1.10.0) lib/multi_json/adapters/oj.rb:15:in `load'
multi_json (1.10.0) lib/multi_json/adapters/oj.rb:15:in `load'
multi_json (1.10.0) lib/multi_json/adapter.rb:20:in `load'
multi_json (1.10.0) lib/multi_json.rb:119:in `load'
activesupport (3.2.18) lib/active_support/json/decoding.rb:15:in `decode'
actionpack (3.2.18) lib/action_dispatch/middleware/params_parser.rb:47:in `parse_formatted_parameters'
actionpack (3.2.18) lib/action_dispatch/middleware/params_parser.rb:17:in `call'
actionpack (3.2.18) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
actionpack (3.2.18) lib/action_dispatch/middleware/cookies.rb:341:in `call'
actionpack (3.2.18) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.18) lib/active_support/callbacks.rb:405:in `_run__2251076412730968111__call__14609921253459192__callbacks'
activesupport (3.2.18) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.18) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.18) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.18) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.18) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.18) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.18) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.18) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.18) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.18) lib/rails/rack/logger.rb:18:in `call'
actionpack (3.2.18) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.5) lib/rack/runtime.rb:17:in `call'
rack (1.4.5) lib/rack/lock.rb:15:in `call'
actionpack (3.2.18) lib/action_dispatch/middleware/static.rb:63:in `call'
railties (3.2.18) lib/rails/engine.rb:484:in `call'
railties (3.2.18) lib/rails/application.rb:231:in `call'
railties (3.2.18) lib/rails/railtie/configurable.rb:30:in `method_missing'
rack (1.4.5) lib/rack/lint.rb:48:in `_call'
rack (1.4.5) lib/rack/lint.rb:36:in `call'
rack (1.4.5) lib/rack/showexceptions.rb:24:in `call'
rack (1.4.5) lib/rack/commonlogger.rb:33:in `call'
rack (1.4.5) lib/rack/chunked.rb:43:in `call'
rack (1.4.5) lib/rack/content_length.rb:14:in `call'
unicorn (4.8.3) lib/unicorn/http_server.rb:576:in `process_client'
unicorn (4.8.3) lib/unicorn/http_server.rb:670:in `worker_loop'
unicorn (4.8.3) lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
unicorn (4.8.3) lib/unicorn/http_server.rb:140:in `start'
unicorn (4.8.3) bin/unicorn:126:in `<top (required)>'
```

I've done some debugging myself and i found out that:
- We get the same error with v2.9.1 but not with v2.9.0
- We only get the error when running with unicorn
- The exception is not raised when running Rails v4.1

I managed to reproduce the error with this small app:
### config.ru

``` ruby
require "action_controller/railtie"
require "oj"

class Dummy < Rails::Application
  config.root = File.dirname(__FILE__)
  config.secret_token = "****************************************"
  config.logger = Logger.new(File.expand_path('../test.log', __FILE__))
  Rails.logger = config.logger
  config.consider_all_requests_local = true

  routes.draw do
    post "/" => proc { |env| [200, { "Content-Type" => "text/plain" }, ["OK"]] }
  end
end

run Dummy
```
### Gemfile

``` ruby
source "https://rubygems.org"

gem "rails", "= 3.2.18"
gem "oj", "= 2.9.1"
gem "unicorn", "= 4.8.3"
```

```
bundle exec unicorn
```

```
 curl 'http://localhost:8080/' -H 'Content-Type: application/json' --data-binary '{"hello": "world"}'
```
