### ISSUE TITLE
Error in dump.c when building OJ 2.17.5 on rubinius 2.5.8

### ISSUE THREAD

**Issue by chriso0710** [ohler55/oj#316]
Hi all,

I am having trouble building OJ 2.17.5 on rubinius 2.5.8 (build with llvm-3.5).
Any ideas how to solve this?

Thanks
Christian

```
Installing oj 2.17.5 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/co/.rvm/rubies/rbx-2.5.8/bin/rbx -r ./siteconf20161111-39769-1w26l84.rb extconf.rb
>>>>> Creating Makefile for rubinius version 2.1.0 on x86_64-darwin13.4.0 <<<<<
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling cache8.c
compiling circarray.c
compiling compat.c
compiling dump.c
dump.c:1346:10: warning: implicit declaration of function 'rb_obj_method_arity' is invalid in C99 [-Wimplicit-function-declaration]
        switch (rb_obj_method_arity(obj, oj_as_json_id)) {
                ^
dump.c:1960:61: error: too few arguments to function call, expected 6, have 5
            dump_val(rb_struct_aref(obj, INT2FIX(i)), d3, out, 0, 0);
            ~~~~~~~~                                               ^
dump.c:62:1: note: 'dump_val' declared here
static void     dump_val(VALUE obj, int depth, Out out, int argc, VALUE *argv, bool as_ok);
^
1 warning and 1 error generated.
make: *** [dump.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/co/.rvm/gems/rbx-2.5.8@mapbot/gems/oj-2.17.5 for inspection.
Results logged to /Users/co/.rvm/gems/rbx-2.5.8@mapbot/extensions/x86_64-darwin-13/2.1/oj-2.17.5/gem_make.out
An error occurred while installing oj (2.17.5), and Bundler cannot continue.
Make sure that `gem install oj -v '2.17.5'` succeeds before bundling.
```

```
$ ruby -v
rubinius 2.5.8 (2.1.0 bef51ae3 2015-07-14 3.5.2 JI) [x86_64-darwin13.4.0]
```

**Comment by ohler55** [comment]
I't been a while since I tried to build with rbx. I hadn't been able to build the more recent versions. I'll give it another try. It looks like some compile flags need to be set to not use rb_obj_method_arity() function assuming there is an alternative.

**Comment by chriso0710** [comment]
OK, thanks. Looks like I will have to go back to MRI for now...

**Comment by ohler55** [comment]
I have an older version of rbx on my machine. rbx 2.2.6 that shows the same problem so I should be able to get it fixed. I'll try on Ubuntu as well. I was not able to install rbx-2.5.8 nor the latests, rbx-3.9 on macOS Sierra. Apparently rbx uses sys call() which is deprecated to the extent that macOS exits with an error.

**Comment by ohler55** [comment]
I fixed the compile errors on rbx-2.2.6. Please try it on your version of RBX.
